### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by not-my-profile** [vxern/romanian#5]
README.md contains 3 broken links:

* https://scoala.bibliotecapemobil.ro/biblioteca.php | Failed: Network error: dns error: no record found for Query { name: Name("scoala.bibliotecapemobil.ro.home."), query_type: AAAA, query_class: IN }
* https://publika.md/ | Failed: Network error: dns error: no record found for Query { name: Name("publika.md.home."), query_type: AAAA, query_class: IN }
* https://youtube.com/watch?v=iuo4MmYimHw | Failed: Network error: Not Found

(As reported by [lychee](https://crates.io/crates/lychee)).

**Comment by vxern** [comment]
Regarding publika.md, according to Wikipedia:
> Licența i-a fost suspendată pe 30 octombrie 2023, dar continuă să emită online.
> Its licence was suspended on 30 October 2023, but it continues to emit online.
Doesn't sound optimistic.

**Comment by vxern** [comment]
Turns out publika.md is now publika.press, deleting the rest.
